platform :ios, '15.0'
use_frameworks!

project 'VoiceVerifier/VoiceVerifier.xcodeproj'

target 'VoiceVerifier' do
  pod 'LibTorch', '2.1.0'   # or just pod 'LibTorch'
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end